spring:
  application:
    name: rapid-engine

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:19092}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    properties:
      sasl.mechanism: "${KAFKA_SASL_MECHANISM:PLAIN}"
      sasl.jaas.config: "${KAFKA_SASL_JAAS_CONFIG:}"
      ssl.endpoint.identification.algorithm: "${KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:https}"
      ssl.truststore.location: "${KAFKA_SSL_TRUSTSTORE_LOCATION:}"
      ssl.truststore.password: "${KAFKA_SSL_TRUSTSTORE_PASSWORD:}"
      ssl.truststore.type: "${KAFKA_SSL_TRUSTSTORE_TYPE:JKS}"
      ssl.keystore.location: "${KAFKA_SSL_KEYSTORE_LOCATION:}"
      ssl.keystore.password: "${KAFKA_SSL_KEYSTORE_PASSWORD:}"
      ssl.keystore.type: "${KAFKA_SSL_KEYSTORE_TYPE:JKS}"
      ssl.key.password: "${KAFKA_SSL_KEY_PASSWORD:}"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      properties:
        enable.idempotence: true
    admin:
      auto-create: true

app:
  messaging:
    broker: ${MESSAGING_BROKER}

  rabbitmq:
    matches:
      exchange: ${RABBITMQ_MATCHES_EXCHANGE:matches.exchange}
      queue: ${RABBITMQ_MATCHES_QUEUE:matches.queue}
      routing-key: ${RABBITMQ_MATCHES_ROUTING_KEY:matches.routing.key}
    results:
      exchange: ${RABBITMQ_RESULTS_EXCHANGE:results.exchange}
      queue: ${RABBITMQ_RESULTS_QUEUE:results.queue}
      routing-key: ${RABBITMQ_RESULTS_ROUTING_KEY:results.routing.key}

  kafka:
    matches-topic: ${KAFKA_MATCHES_TOPIC:matches.topic}
    results-topic: ${KAFKA_RESULTS_TOPIC:results.topic}
    partitions: ${KAFKA_PARTITIONS:1}
    replication-factor: ${KAFKA_REPLICATION_FACTOR:1}

  rundown-api:
    key: ${RUNDOWN_API_KEY}
    host: ${RUNDOWN_BASE_URL}
    sports-id: ${RUNDOWN_SPORT_IDS}
    affiliate-id: ${AFFILIATE_IDS}
    poll: ${POLL}
    delay: ${DELAY}

server:
  port: ${APP_PORT}

logging:
  config: classpath:rapid-engine-logback.xml
  level:
    root: INFO
    com.bixx.rapid_engine: INFO
    org.apache.coyote: INFO
    org.springframework.jdbc: ${LOGGING_LEVEL}

log:
  path: ${LOG_PATH}
