spring:
  application:
    name: rapid-engine

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: /

app:
  rabbitmq:
    matches:
      exchange: ${RABBITMQ_MATCHES_EXCHANGE}
      queue: ${RABBITMQ_MATCHES_QUEUE}
      routing-key: ${RABBITMQ_MATCHES_ROUTING_KEY}

    results:
      exchange: ${RABBITMQ_RESULTS_EXCHANGE}
      queue: ${RABBITMQ_RESULTS_QUEUE}
      routing-key: ${RABBITMQ_RESULTS_ROUTING_KEY}

  rundown-api:
    key: ${RUNDOWN_API_KEY}
    #    key: ${RUNDOWN_API_KEY_M1}
    host: ${RUNDOWN_BASE_URL}
    sports-id: ${RUNDOWN_SPORT_IDS}
    affiliate-id: ${AFFILIATE_IDS}
    poll: ${POLL}
    delay: ${DELAY}

server:
  port: ${APP_PORT}

logging:
  config: classpath:rapid-engine-logback.xml
  level:
    root: INFO
    com.bixx.rapid_engine: INFO
    org.apache.coyote: INFO
    org.springframework.jdbc: ${LOGGING_LEVEL}

log:
  path: ${LOG_PATH}
